version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/github-actions): "
    labels:
      - dependabot
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps/npm): "
    labels:
      - dependabot
